home/urls.py
from django.urls import path
from . import views
urlpatterns= [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),  # Asegúrate de que esta línea esté presente
    path('logout/', views.logout, name='logout'), 
    path('profile/', views.profile, name='profile'),
]

registros/urls.py
from django.urls import path
from . import views

urlpatterns =[
    path('registro_productos/', views.registro_productos, name='registro_productos'),
    path('registro_clientes/', views.registro_clientes, name='registro_clientes'),
    path('crear_pedido/', views.crear_pedido, name='crear_pedido'),
    path('registro_categoria/', views.registro_categoria, name='registro_categoria'),
]

ventas_deliverysnk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')), 
    path('registros/', include('registros.urls')),
    path('vistas/', include('vistas.urls')),
    path('finanzas_personales/', include('finanzas_personales.urls')),
  
]

registros/models.py
from django.db import models

class Cliente(models.Model):
    nombre = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=100)
    fecha_registro = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.nombre} {self.apellidos}"
    
class Categorias(models.Model):
    nombre = models.CharField(max_length=100)
    fecha_registro = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.nombre}"
    
class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    categoria = models.ForeignKey(Categorias, on_delete=models.CASCADE, null=True, related_name='productos')
    precio_compra = models.DecimalField(max_digits=10, decimal_places=2)
    precio_venta = models.DecimalField(max_digits=10, decimal_places=2)
    ganancia = models.DecimalField(max_digits=10, decimal_places=2)
    fecha_registro = models.DateField(auto_now_add=True)

    def calcular_ganancia(self):
        self.ganancia = self.precio_venta - self.precio_compra
        return self.ganancia

    def save(self, *args, **kwargs):
        self.calcular_ganancia()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.nombre
    
class Talla(models.Model):
    talla = models.CharField(max_length=5)

    def __str__(self):
        return f"Talla: {self.talla}"
    
class Pedido(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=True, blank=False, related_name='cliente')
    productos = models.ManyToManyField(Producto, through='PedidoProducto', related_name='pedidos')
    enganche = models.DecimalField(max_digits=10, decimal_places=2)
    fecha_realizacion = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"Pedido de {self.cliente} realizado el {self.fecha_realizacion}"

class PedidoProducto(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE, related_name='pedido_productos')
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    talla = models.ForeignKey(Talla, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.producto.nombre} - Talla: {self.talla.talla}"


    
class Abono(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE, related_name='abonos')
    cantidad = models.DecimalField(max_digits=10, decimal_places=2)
    fecha = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"Abono de {self.cantidad} para el pedido {self.pedido.id}"

registros/forms.py
from django import forms
from .models import Producto, Cliente, Pedido, Categorias, Talla, PedidoProducto
from django_select2.forms import Select2Widget


class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nombre', 'apellidos']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'apellidos': forms.TextInput(attrs={'class': 'form-control'}),
        }

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categorias
        fields = ['nombre']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
        }

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['nombre', 'categoria', 'precio_compra', 'precio_venta']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'categoria': forms.Select(attrs={'class': 'form-control'}),
            'precio_compra': forms.NumberInput(attrs={'class': 'form-control'}),
            'precio_venta': forms.NumberInput(attrs={'class': 'form-control'}),
        }

class PedidoForm(forms.ModelForm):
    class Meta:
        model = Pedido
        fields = ['cliente', 'enganche']
        widgets = {
            'cliente': Select2Widget,
        }

class PedidoProductoForm(forms.ModelForm):
    class Meta:
        model = PedidoProducto
        fields = ['producto', 'talla']
        widgets = {
            'talla': forms.TextInput(attrs={'placeholder': 'Ingrese la talla'}),
        }

registros/views.py
from django.shortcuts import render, redirect
from .forms import ProductoForm, ClienteForm, PedidoForm, CategoriaForm, PedidoProductoForm
from .models import Producto, PedidoProducto, Talla
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponse
from django.http import JsonResponse
def is_superuser(user):
    return user.is_superuser

@login_required
def registro_productos(request):
    if request.method == 'POST':
        form = ProductoForm(request.POST)
        if form.is_valid():
            form.save()
            # Si es una solicitud AJAX, responder con JSON
            if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
                return JsonResponse({'message': 'Producto registrado.'}, status=200)
            # Si no es AJAX, redirigir como de costumbre
            return redirect('registro_productos')
    else:
        form = ProductoForm()
    
    return render(request, 'registro_productos.html', {'form': form})


@login_required
@user_passes_test(is_superuser)
def registro_clientes(request):
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            # Si es una solicitud AJAX, responder con JSON
            if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
                return JsonResponse({'message': 'Cliente registrado.'}, status=200)
            # Si no es AJAX, redirigir como de costumbre
            return redirect('registro_cliente')
    else:
        form = ClienteForm()

    return render(request, 'registro_clientes.html', {'form': form})

@login_required
@user_passes_test(is_superuser)
def crear_pedido(request):
    if request.method == 'POST':
        form = PedidoForm(request.POST)
        if form.is_valid():
            # Crear el pedido
            pedido = form.save()

            # Obtener los productos y las tallas seleccionadas
            productos = request.POST.getlist('productos')  # Lista de productos
            tallas = request.POST.getlist('tallas')  # Lista de tallas

            # Verificar que las listas de productos y tallas tengan la misma longitud
            if len(productos) != len(tallas):
                return HttpResponse("Error: la cantidad de productos y tallas no coincide", status=400)

            # Asociar cada producto con su respectiva talla
            for producto_id, talla in zip(productos, tallas):
                producto = Producto.objects.get(id=producto_id)
                talla_obj, created = Talla.objects.get_or_create(talla=talla)
                PedidoProducto.objects.create(pedido=pedido, producto=producto, talla=talla_obj)

            # Redirigir a una página de éxito o al detalle del pedido
            return redirect('detalle_pedido', pedido_id=pedido.id)  # Redirige al detalle del pedido
    else:
        form = PedidoForm()
        productos = Producto.objects.all()

    return render(request, 'crear_pedido.html', {'form': form, 'productos': productos})


@login_required
@user_passes_test(is_superuser)
def registro_categoria(request):
    if request.method == 'POST':
        form = CategoriaForm(request.POST)
        if form.is_valid():
            form.save()

            # Si es una solicitud AJAX, responder con JSON
            if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
                return JsonResponse({'message': 'Categoría registrada.'}, status=200)

            # Si no es AJAX, redirigir como de costumbre
            return redirect('registro_categoria')
    else:
        form = CategoriaForm()

    return render(request, 'registro_categoria.html', {'form': form})

registros/templates/confirmar_eliminar_categoria.html
{% extends 'navbar.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Eliminar Categoría</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            background-image: url("{% static 'images/Delivery_perfil_01.png' %}");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            height: 100vh;
            color: white;
            background-attachment: fixed;
        }
        .form-container {
            max-width: 600px;
            margin: auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            background: linear-gradient(to bottom, rgba(247, 247, 247, 0.993), rgba(247, 247, 247, 0.904));
            color: black;
        }
        .btn-custom {
            background-color: #B0AEAD;
            border-color: #B0AEAD;
            color: black; /* Cambia el color del texto si es necesario */
        }
        .btn-custom:hover {
            background-color: black; /* Un par de tonos más oscuro */
            border-color: black;
            color: white;
        }
    </style>
</head>
<body>
    <div class="form-container">
        <h1 class="text-center">Eliminar Categoría</h1>
        <p>¿Estás seguro de que deseas eliminar la categoría {{ categoria.nombre }}?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Eliminar</button>
            <a href="{% url 'lista_categorias' %}" class="btn btn-custom">Cancelar</a>
        </form>
    </div>
</body>
</html>
{% endblock %}

registros/templates/confirmar_eliminar_cliente.html
{% extends 'navbar.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Eliminar Cliente</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            background-image: url("{% static 'images/Delivery_perfil_01.png' %}");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            height: 100vh;
            color: white;
            background-attachment: fixed;

        }
        .form-container {
            max-width: 600px;
            margin: auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            background: linear-gradient(to bottom, rgba(247, 247, 247, 0.993), rgba(247, 247, 247, 0.904));
            color: black;
        }
        .btn-custom {
            background-color: #B0AEAD;
            border-color: #B0AEAD;
            color: black; /* Cambia el color del texto si es necesario */
        }

        .btn-custom:hover {
            background-color: black; /* Un par de tonos más oscuro */
            border-color: black;
            color: white;
        }
    </style>
</head>
<body>
    <div class="form-container">
        <h1 class="text-center">Eliminar Cliente</h1>
        <p>¿Estás seguro de que deseas eliminar al cliente {{ cliente.nombre }} {{ cliente.apellidos }}?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Eliminar</button>
            <a href="{% url 'lista_clientes' %}" class="btn btn-custom">Cancelar</a>
        </form>
    </div>
</body>
</html>
{% endblock %}

registros/templates/confirmar_eliminar_pedido.html
{% extends 'navbar.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Eliminar Pedido</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            background-image: url("{% static 'images/Delivery_perfil_01.png' %}");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            height: 100vh;
            color: white;
            background-attachment: fixed;

        }
        .form-container {
            max-width: 600px;
            margin: auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            background: linear-gradient(to bottom, rgba(247, 247, 247, 0.993), rgba(247, 247, 247, 0.904));
            color: black;
        }
        .btn-custom {
            background-color: #B0AEAD;
            border-color: #B0AEAD;
            color: black; /* Cambia el color del texto si es necesario */
        }

        .btn-custom:hover {
            background-color: black; /* Un par de tonos más oscuro */
            border-color: black;
            color: white;
        }
    </style>
</head>
<body>
    <div class="form-container">
        <h1 class="text-center">Eliminar Pedido</h1>
        <p>¿Estás seguro de que deseas eliminar el pedido de {{ pedido.cliente }}?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Eliminar</button>
            <a href="{% url 'detalle_pedido' pedido.id %}" class="btn btn-custom">Cancelar</a>
        </form>
    </div>
</body>
</html>
{% endblock %}

registros/templates/confirmar_eliminar_producto.html
{% extends 'navbar.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Eliminar Producto</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            background-image: url("{% static 'images/Delivery_perfil_01.png' %}");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            height: 100vh;
            color: white;
            background-attachment: fixed;

        }
        .form-container {
            max-width: 600px;
            margin: auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            background: linear-gradient(to bottom, rgba(247, 247, 247, 0.993), rgba(247, 247, 247, 0.904));
            color: black;
        }
        .btn-custom {
            background-color: #B0AEAD;
            border-color: #B0AEAD;
            color: black; /* Cambia el color del texto si es necesario */
        }

        .btn-custom:hover {
            background-color: black; /* Un par de tonos más oscuro */
            border-color: black;
            color: white;
        }
    </style>
</head>
<body>
    <div class="form-container">
        <h1 class="text-center">Eliminar Producto</h1>
        <p>¿Estás seguro de que deseas eliminar el producto {{ producto.nombre }}?</p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Eliminar</button>
            <a href="{% url 'lista_productos' %}" class="btn btn-custom">Cancelar</a>
        </form>
    </div>
</body>
</html>
{% endblock %}

registros/templates/crear_pedido.html
{% extends 'navbar.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Formulario de Pedido</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
    <style>
        body {
            background-image: url("{% static 'images/Delivery_perfil_01.png' %}");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            height: 100vh;
            color: white;
            background-attachment: fixed;
        }
        .form-container {
            max-width: 600px;
            margin: auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            background: linear-gradient(to bottom, rgba(247, 247, 247, 0.993), rgba(247, 247, 247, 0.904));
            color: black;
        }
        .btn-custom {
            background-color: black;
            border-color: black;
            color: white;
        }
        .btn-custom:hover {
            background-color: #B0AEAD;
            border-color: #B0AEAD;
        }
        /* Estilo personalizado para Select2 */
        .select2-container--default .select2-selection--single .select2-selection__rendered {
            color: black; /* Color del texto en el campo de selección */
        }
        .select2-container--default .select2-results__option {
            color: black; /* Color del texto en las opciones desplegables */
        }
        .select2-container--default .select2-results__option--highlighted {
            background-color: #f0f0f0; /* Color de fondo para opción resaltada */
            color: black; /* Color del texto en opción resaltada */
        }
    </style>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#id_cliente').select2({
                placeholder: "Selecciona un cliente",
                allowClear: true
            });

            $('#productos').select2({
                placeholder: "Selecciona un producto",
                allowClear: true
            });
        });

        function agregarProducto() {
            var selectProducto = document.getElementById("productos");
            var inputTalla = document.getElementById("talla");
            var selectedProducto = selectProducto.options[selectProducto.selectedIndex];
            var talla = inputTalla.value;

            if (talla === "") {
                alert("Por favor, ingrese una talla.");
                return;
            }

            var listaProductos = document.getElementById("lista-productos");
            var item = document.createElement("li");
            item.textContent = selectedProducto.text + " - Talla: " + talla;
            listaProductos.appendChild(item);

            // Crear campos ocultos para almacenar los productos y tallas seleccionados
            var productosSeleccionados = document.getElementById("productosSeleccionados");
            var tallasSeleccionadas = document.getElementById("tallasSeleccionadas");

            var inputProducto = document.createElement("input");
            inputProducto.type = "hidden";
            inputProducto.name = "productos";
            inputProducto.value = selectedProducto.value;
            productosSeleccionados.appendChild(inputProducto);

            var inputTallaOculto = document.createElement("input");
            inputTallaOculto.type = "hidden";
            inputTallaOculto.name = "tallas";
            inputTallaOculto.value = talla;
            tallasSeleccionadas.appendChild(inputTallaOculto);

            // Limpiar el campo de talla
            inputTalla.value = "";
        }
    </script>
</head>
<body>
    <div class="form-container">
        <h1 class="text-center">Formulario de Pedido</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="form-group">
                <label for="productos">Productos</label>
                <select class="form-control" id="productos" name="producto">
                    {% for producto in productos %}
                        <option value="{{ producto.id }}">{{ producto.nombre }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="talla">Talla</label>
                <input type="text" class="form-control" id="talla" name="talla">
                <button type="button" class="btn btn-secondary mt-2" onclick="agregarProducto()">Agregar Producto</button>
            </div>
            
            <div class="form-group">
                <label for="lista-productos">Productos Seleccionados</label>
                <ul id="lista-productos" class="list-group">
                    <!-- Aquí se agregarán los productos seleccionados -->
                </ul>
            </div>
            <!-- Inputs ocultos para almacenar los productos y tallas seleccionados -->
            <div id="productosSeleccionados"></div>
            <div id="tallasSeleccionadas"></div>
            
            <button type="submit" class="btn btn-custom">Guardar</button>
        </form>
    </div>
</body>
</html>
{% endblock %}

registros/templates/editar_categoria.html
{% extends 'navbar.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Editar Categoría</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            background-image: url("{% static 'images/Delivery_perfil_01.png' %}");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            height: 100vh;
            color: white;
            background-attachment: fixed;
        }
        .form-container {
            max-width: 600px;
            margin: auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            background: linear-gradient(to bottom, rgba(247, 247, 247, 0.993), rgba(247, 247, 247, 0.904));
            color: black;
        }
        .btn-custom {
            background-color: #B0AEAD;
            border-color: #B0AEAD;
            color: black; /* Cambia el color del texto si es necesario */
        }
        .btn-custom:hover {
            background-color: black; /* Un par de tonos más oscuro */
            border-color: black;
            color: white;
        }
    </style>
</head>
<body>
    <div class="form-container">
        <h1 class="text-center">Editar Categoría</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-custom">Guardar Cambios</button>
        </form>
    </div>
</body>
</html>
{% endblock %}

registros/templates/editar_cliente.html
{% extends 'navbar.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Editar Cliente</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            background-image: url("{% static 'images/Delivery_perfil_01.png' %}");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            height: 100vh;
            color: white;
            background-attachment: fixed;

        }
        .form-container {
            max-width: 600px;
            margin: auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            background: linear-gradient(to bottom, rgba(247, 247, 247, 0.993), rgba(247, 247, 247, 0.904));
            color: black;
        }
        .btn-custom {
            background-color: #B0AEAD;
            border-color: #B0AEAD;
            color: black; /* Cambia el color del texto si es necesario */
        }

        .btn-custom:hover {
            background-color: black; /* Un par de tonos más oscuro */
            border-color: black;
            color: white;
        }
    </style>
</head>
<body>
    <div class="form-container">
        <h1 class="text-center">Editar Cliente</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-custom">Guardar Cambios</button>
        </form>
    </div>
</body>
</html>
{% endblock %}

registros/templates/editar_pedido.html
{% extends 'navbar.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Editar Pedido</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            background-image: url("{% static 'images/Delivery_perfil_01.png' %}");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            height: 100vh;
            color: white;
            background-attachment: fixed;

        }
        .form-container {
            max-width: 600px;
            margin: auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            background: linear-gradient(to bottom, rgba(247, 247, 247, 0.993), rgba(247, 247, 247, 0.904));
            color: black;
        }
        .btn-custom {
            background-color: #B0AEAD;
            border-color: #B0AEAD;
            color: black; /* Cambia el color del texto si es necesario */
        }

        .btn-custom:hover {
            background-color: black; /* Un par de tonos más oscuro */
            border-color: black;
            color: white;
        }
    </style>
    <script>
        function agregarProducto() {
            var selectProducto = document.getElementById("productos");
            var inputTalla = document.getElementById("talla");
            var selectedProducto = selectProducto.options[selectProducto.selectedIndex];
            var talla = inputTalla.value;
            var listaProductos = document.getElementById("lista-productos");

            var item = document.createElement("li");
            item.textContent = selectedProducto.text + " - Talla: " + talla;
            item.setAttribute("data-producto-id", selectedProducto.value);
            item.setAttribute("data-talla", talla);

            var deleteButton = document.createElement("button");
            deleteButton.textContent = "Eliminar";
            deleteButton.className = "btn btn-danger btn-sm ml-2";
            deleteButton.onclick = function() {
                listaProductos.removeChild(item);
            };

            item.appendChild(deleteButton);
            listaProductos.appendChild(item);
        }
    </script>
</head>
<body>
    <div class="form-container">
        <h1 class="text-center">Editar Pedido</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="form-group">
                <label for="productos">Productos</label>
                <select class="form-control" id="productos" name="productos">
                    {% for producto in productos %}
                        <option value="{{ producto.id }}">{{ producto.nombre }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="talla">Talla</label>
                <input type="text" class="form-control" id="talla" name="tallas">
                <button type="button" class="btn btn-secondary mt-2" onclick="agregarProducto()">Agregar Producto</button>
            </div>
            <div class="form-group">
                <label for="lista-productos">Productos Seleccionados</label>
                <ul id="lista-productos" class="list-group">
                    <!-- Aquí se agregarán los productos seleccionados -->
                </ul>
            </div>
            <button type="submit" class="btn btn-custom">Guardar Cambios</button>
        </form>
    </div>
</body>
</html>
{% endblock %}

registros/templates/editar_producto.html
{% extends 'navbar.html' %}
{% load static %}

{% block content %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Editar Producto</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            background-image: url("{% static 'images/Delivery_perfil_01.png' %}");
            background-size: cover;
            background-position: center;
            background-repeat: no-repeat;
            height: 100vh;
            color: white;
            background-attachment: fixed;

        }
        .form-container {
            max-width: 600px;
            margin: auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            background: linear-gradient(to bottom, rgba(247, 247, 247, 0.993), rgba(247, 247, 247, 0.904));
            color: black;
        }
        .btn-custom {
            background-color: #B0AEAD;
            border-color: #B0AEAD;
            color: black; /* Cambia el color del texto si es necesario */
        }

        .btn-custom:hover {
            background-color: black; /* Un par de tonos más oscuro */
            border-color: black;
            color: white;
        }
    </style>
</head>
<body>
    <div class="form-container">
        <h1 class="text-center">Editar Producto</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-custom">Guardar Cambios</button>
        </form>
    </div>
</body>
</html>
{% endblock %}